### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by szpak** [MatthewTamlin/Retrial#12]
It would be handy to provide a changelog file with all changes between releases.

Content of that file could be sync with GitHub release notes with [Chandler](https://github.com/mattbrictson/chandler/) (or some other tool). You can in one of my projects how it can look in [code](https://github.com/szpak/CDeliveryBoy/blob/master/gradle/cdeliveryboy-release.gradle#L99-L114).

**Comment by MatthewTamlin** [comment]
The effort to set this up would be unnecessary for such a small project. I'll just write the changelogs manually.
