### ISSUE TITLE
RuntimeException: Cannot calculate hash for empty file

### ISSUE THREAD

**Issue by szpak** [MatthewTamlin/Retrial#15]
It would be good to add a file name to the exception message to make getting know what caused that problem easier.

```
Caused by: java.lang.RuntimeException: Cannot calculate hash for empty file.
        at com.matthewtamlin.retrial.hash.Sha512HashGenerator$generateHash$1.call(Sha512HashGenerator.kt:36)
        at com.matthewtamlin.retrial.hash.Sha512HashGenerator$generateHash$1.call(Sha512HashGenerator.kt:28)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
```

Code to reproduce that issue: https://github.com/szpak/gradle-pitest-plugin/tree/tech/retrial

Please note that you need to add `retrail.jar` on your own. Pushing to the remote repository I noticed that it takes 50M+. I have to consider if it is not too much for my git repo.

As a side note I was wondering what do you do with the dependencies having JAR at 50KB of size (I noticed KB -> MB on long lasting push :) ). As you use Kotlin and RxJava it may be hard. Maybe at least Kotlin could be taken from the Gradle dependencies itself (if provided as of 4.x)?

**Comment by MatthewTamlin** [comment]
Thanks, I'll add some info about the file that's causing the issue.

Regarding the size of the jar, it's an unfortunate side effect of using shadowjar to make it entirely self-contained. I was trying to get proguard minification working to remove the unused classes, but the Gradle API dependency is causing issues. I'll revisit proguard when I have more time.

**Comment by MatthewTamlin** [comment]
Accidentally linked PR to this by mistake.
